Feature/dark mode
yellowme/youst-kotlin pull request #61
Opened 2019-11-09 17:15 UTC by marioguillermo

## What does this PR do?
- Add new color palette
- Add dark-mode
- Add animation for dark-mode

## How should this be manually tested?
- By clicking this link in the phone https://yellowme.github.io/theme?wanted=dark the theme should change to dark. Close and open the app, the change should persist.
- By clicking this link in the phone https://yellowme.github.io/theme?wanted=light the theme should change to light. Close and open the app, the change should persist.

## What are the relevant tickets?
closes  #56

2019-11-11 16:11 UTC, luisburgos requested changes

2019-11-11 16:11 UTC, luisburgos commented on app/src/main/java/mx/yellowme/youst/splash/SplashActivity.kt
> +            setAnimation(rawRes)
Me iría por combinar el algunas cosas aquí:

```
setAnimation(if (hasDarkTheme() {
    R.raw.logo_reveal_dark
} else {
    R.raw.logo_reveal
})
```

Eso implica agregar la función `hasDarkTheme`, al leer `themeId()` por si solo me quedó la duda sobre a que hacia referencia, por lo mismo creo que `hasDarkTheme` pudiera tener algo más para complementar el nombre

2019-11-11 16:11 UTC, LuisBurgos commented on app/src/main/java/mx/yellowme/youst/splash/SplashActivity.kt
> +    }
El enfoque de la función `handleUri`  me deja pensando en:

¿Por qué manejamos un `let` para un booleano? 

Probablemente podemos hacer un return si combinamos algunas líneas 🤔 O tal vez ¿Podríamos manejar un tema por defecto?

2019-11-11 16:11 UTC, LuisBurgos commented on challenges/src/main/AndroidManifest.xml
> +                    android:path="/hello" />
¿Este data sigue siendo necesario?

2019-11-11 16:11 UTC, LuisBurgos commented on core/src/main/java/mx/yellowme/youst/core/components/ThemeHelper.kt
> +    const val THEME_QUERY = "wanted"
Por qué la llave es `THEME_QUERY` y el valor es `wanted` ? 🤔

2019-11-11 16:11 UTC, LuisBurgos commented on core/src/main/java/mx/yellowme/youst/core/extensions/ActivityExtensions.kt
> +}
¿Este es el nuevo enfoque de acceso a las preferencias?

2019-11-11 16:11 UTC, LuisBurgos commented on core/src/main/java/mx/yellowme/youst/core/hooks/BaseActivity.kt
> +        when (themeName) {
¿Esta función no falla si le paso cualquier otro Int? ¿Tenemos algún theme por defecto en cualquier caso?

2019-11-11 16:11 UTC, LuisBurgos commented on core/src/main/java/mx/yellowme/youst/core/hooks/BaseActivity.kt
> +        if (getBooleanFrom(
Me iría por crear una función más verbose algo como`isDarkThemeEnabled` o similar, ¿Qué opinas?

2019-11-11 16:11 UTC, LuisBurgos commented on core/src/main/res/values/colors.xml
> +<!--    <color name="guitar_light_black">#546165</color>-->
Podemos remover estos colores dado que ya no los utilizaremos

2019-11-11 16:11 UTC, LuisBurgos commented on core/src/main/res/values/colors.xml
> +    <!--endregion-->
Podemos hacer un Find Usages para este archivo y remover los colores que ya no se usen

2019-11-11 16:11 UTC, LuisBurgos commented on core/src/main/res/values/styles.xml
> +
Todos los espacios te los marca tu Android Studio?, me iría por dejar juntos los que son `Dashboard`, luego otro grupo de los que son `Challenge`, y así, solo espacios entre grupos y no entre elementos.

2019-11-11 16:35 UTC, marioguillermo commented on challenges/src/main/AndroidManifest.xml
> +                    android:path="/hello" />
Creo 🤔 no yo lo agregue. Solo cambie el host. De hecho debería estar el de yellow

2019-11-11 16:35 UTC, marioguillermo commented on core/src/main/java/mx/yellowme/youst/core/components/ThemeHelper.kt
> +    const val THEME_QUERY = "wanted"
Son los nombres que se me ocurrieron 
https://marioguillermo.github.io/theme?`wanted`=dark <- es para hacer referencia a este param de la query

2019-11-11 16:35 UTC, marioguillermo commented on core/src/main/java/mx/yellowme/youst/core/extensions/ActivityExtensions.kt
> +}
No realmente, aun no pienso en ese enfoque.

2019-11-11 16:35 UTC, marioguillermo commented on core/src/main/java/mx/yellowme/youst/core/hooks/BaseActivity.kt
> +        when (themeName) {
Deja el tema que esta definido en el manifest

2019-11-11 16:35 UTC, marioguillermo commented on core/src/main/res/values/styles.xml
> +
Cuando se hizo el format se agregaron, los puedo remover

2019-11-11 19:25 UTC, LuisBurgos commented on core/src/main/java/mx/yellowme/youst/core/components/ThemeHelper.kt
> +    const val THEME_QUERY = "wanted"
Pudo ser algo como `style`, `option` ?

2019-11-11 19:26 UTC, LuisBurgos commented on core/src/main/java/mx/yellowme/youst/core/extensions/ActivityExtensions.kt
> +}
Puedes ponerle un todo para refactorizarlo en un futuro? Cuando determinemos un enfoque

2019-11-11 19:30 UTC, marioguillermo commented on core/src/main/java/mx/yellowme/youst/core/components/ThemeHelper.kt
> +    const val THEME_QUERY = "wanted"
sip ahorita lo cambio. Lo siento soy muy malo nombrando cosas 😞

2019-11-20 16:14 UTC, luisburgos approved these changes

2019-11-20 18:09 UTC, merged