Feature/enable dark mode
yellowme/youst-kotlin pull request #67
Opened 2020-04-30 21:23 UTC by kevingamboa17

---
name: Enable Dark Mode
about: Finish the implementation of the dark mode and save the user preference about the 
title: "Enable dark mode"
labels:  
assignees: @LuisBurgos  @marioguillermo  @AdrianLeyva  @cesargom 

---

## What does this PR do?

- Finish the implementation of dark mode
- Add a new Dialog Builder using the Material Dialog
- Add a dialog to select a theme (Dark, Light, Follow system)
- Add selected theme to shared preferences

## Screenshots
![ezgif com-crop (1)](https://user-images.githubusercontent.com/16912316/80760534-abfc8200-8afe-11ea-82a7-d1b2d4882131.gif)

2020-04-30 22:06 UTC, cesargom requested changes

2020-04-30 22:06 UTC, cesargom commented on core/src/main/java/mx/yellowme/youst/core/components/ThemeHelper.kt
> +    fun getIndexOfArray(): Int {
Pregunta: ¿Crees que podrías usar el `ordinal`? Por lo que veo, usas esta función en el array de enums que provee `values`, pero cada valor del enum tiene una propiedad `ordinal` que ya corresponde a su posición en las declaraciones. En ese caso, `LIGHT.ordinal` tendría el valor `0`, `DARK.ordinal` sería `1`, etc, que creo que es lo que quieres hacer aquí. Incluso podrías borrar la función del todo y usar `ordinal` directamente. Aunque también podrías wrappear eso con esta función para mayor claridad. ¿Cómo ves?

2020-05-04 17:58 UTC, kevingamboa17 commented on core/src/main/java/mx/yellowme/youst/core/components/ThemeHelper.kt
> +    fun getIndexOfArray(): Int {
Todo un crack 🙌 
actualizado.

2020-05-04 18:05 UTC, cesargom approved these changes

2020-05-04 18:53 UTC, AdrianLeyva approved these changes
Nice

2020-05-04 19:08 UTC, merged