Add custom interpolator showcase with expanding card views
yellowme/youst-kotlin pull request #68
Opened 2020-05-04 20:12 UTC by cesargom

## What does this PR do?
- New showcase in Playground: Interpolator
- Custom expandable card view
- Custom ease interpolator
- Add an animation listener DSL

## How should this be manually tested?
Open the Interpolator showcase in Youst's Playground and click on the cards.

## Screenshots
![interpolators_low](https://user-images.githubusercontent.com/42198041/81008810-27b94000-8e19-11ea-866e-e99af39c083b.gif)

2020-05-04 21:09 UTC, kevingamboa17 requested changes

2020-05-04 21:09 UTC, kevingamboa17 commented on core/src/main/res/values/colors.xml
> +    <color name="onahau">#CEEEFF</color>
Tal vez estaría cool agregar colores distintos a las tarjetas para el dark mode, también del background, qué opinas?

2020-05-04 21:09 UTC, kevingamboa17 commented on playground/src/main/java/mx/yellowme/youst/playground/ui/widgets/ResizableCardView.kt
> +
Borrar este espacio para mantener la consistencia con el inicio de la clase 🙌

2020-05-04 21:09 UTC, kevingamboa17 commented on playground/src/main/res/layout/resizable_card_view.xml
> +                tools:text="This is a CardView controlled by a LinearInterpolator. Click on it and see how it changes size with a constant speed." />
Este texto no podría ser usado del string resources? 😅

2020-05-05 13:35 UTC, kevingamboa17 submitted a review, later dismissed

2020-05-05 15:11 UTC, marioguillermo commented on playground/src/main/java/mx/yellowme/youst/playground/domain/PlaygroundElement.kt
>  enum class PlaygroundElementType {
Una duda, el id de `PlaygroundElement` tiene que ser un String? Si utilizamos un Int podríamos empezar la cuenta en 0 y usar el ordinal y ya no necesitaríamos crecer el `get()`  de type. Lo único que tendría que ver como tirarse la excepción 🤔

2020-05-05 15:11 UTC, marioguillermo commented on playground/src/main/res/values/attrs_resizable_card.xml
> +    <declare-styleable name="ResizableCardView">
Aqui te aconsejaría que veas que los nombres de tus atributos sean únicos para evitar problemas después 😬

2020-05-05 15:11 UTC, marioguillermo commented on playground/src/main/java/mx/yellowme/youst/playground/domain/PlaygroundElement.kt
>  enum class PlaygroundElementType {
O ya vi es por el JSON, pero igual seria bueno considerarlo 😁

2020-05-05 17:23 UTC, cesargom commented on playground/src/main/java/mx/yellowme/youst/playground/domain/PlaygroundElement.kt
>  enum class PlaygroundElementType {
Justo le hice un comment al respecto a Kevin hace unos días sobre algo similar haha

2020-05-05 17:38 UTC, marioguillermo approved these changes

2020-05-05 19:06 UTC, merged