Add android shortcuts
yellowme/youst-kotlin pull request #71
Opened 2020-05-21 22:01 UTC by kevingamboa17

## What does this PR do?
Add shortcuts to the app

- Add shortcuts
- Add the icons for the shortcuts

## How should this be manually tested?
Install the app and long press the launcher icon, you should see the shortcuts

## Screenshots
![ezgif com-optimize](https://user-images.githubusercontent.com/16912316/82610753-9241de00-9b84-11ea-95b5-483fa8c33926.gif)

2020-05-21 22:59 UTC, luisburgos submitted a review, later dismissed

2020-05-22 17:24 UTC, cesargom requested changes
Newlines at the end of files

2020-05-22 19:35 UTC, AdrianLeyva submitted a review, later dismissed
Nice

2020-05-25 18:56 UTC, cesargom approved these changes

2020-05-25 18:56 UTC, merged